// src/database/seed/seed-data.ts
// Données de seed réalistes pour le contexte Côte d'Ivoire / Afrique de l'Ouest

// ============================================================================
// TENANTS
// ============================================================================
export const tenantsData = [
  {
    tenantCode: 'BAWA-001',
    name: 'Boutique Chez Awa',
    legalName: 'SARL Boutique Chez Awa',
    registrationNumber: 'CI-ABJ-2024-0001',
    taxId: 'CI0001234567',
    businessType: 'BOUTIQUE',
    status: 'ACTIVE',
    subscriptionPlan: 'PROFESSIONAL',
    email: 'contact@chezawa.ci',
    phone: '+225 07 08 09 10 11',
    phoneSecondary: '+225 05 06 07 08 09',
    website: 'https://chezawa.ci',
    address: 'Rue du Commerce, Marcory Zone 4',
    city: 'Abidjan',
    state: 'Lagunes',
    postalCode: '01 BP 1234',
    country: 'CI',
    ownerName: 'Awa Koné',
    ownerEmail: 'awa.kone@chezawa.ci',
    ownerPhone: '+225 07 08 09 10 11',
    subscriptionStartDate: new Date('2024-01-15'),
    subscriptionEndDate: new Date('2025-01-15'),
    trialEndDate: new Date('2024-02-15'),
    monthlyPrice: 25000,
    billingCurrency: 'XOF',
    billingCycle: 'MONTHLY',
    maxUsers: 10,
    maxProducts: 500,
    maxStores: 2,
    maxOrdersPerMonth: 5000,
    storageQuotaGB: 5,
    featureInventory: true,
    featureOrders: true,
    featureDelivery: true,
    featureSuppliers: true,
    featureAdvancedReports: true,
    featurePromotions: true,
    featureMultiStore: false,
    featureApi: false,
    featureAccounting: false,
    defaultLanguage: 'fr',
    timezone: 'Africa/Abidjan',
    dateFormat: 'DD/MM/YYYY',
    primaryColor: '#2E7D32',
    secondaryColor: '#FFA000',
  },
  {
    tenantCode: 'SMBP-002',
    name: 'Super Marché Le Bon Prix',
    legalName: 'SA Super Marché Le Bon Prix',
    registrationNumber: 'CI-ABJ-2023-0456',
    taxId: 'CI0009876543',
    businessType: 'SUPERMARKET',
    status: 'ACTIVE',
    subscriptionPlan: 'ENTERPRISE',
    email: 'info@lebonprix.ci',
    phone: '+225 27 22 44 55 66',
    phoneSecondary: '+225 07 77 88 99 00',
    website: 'https://lebonprix.ci',
    address: 'Boulevard de la République, Plateau',
    city: 'Abidjan',
    state: 'Lagunes',
    postalCode: '01 BP 5678',
    country: 'CI',
    ownerName: 'Moussa Diallo',
    ownerEmail: 'moussa.diallo@lebonprix.ci',
    ownerPhone: '+225 07 77 88 99 00',
    subscriptionStartDate: new Date('2023-06-01'),
    subscriptionEndDate: new Date('2025-06-01'),
    trialEndDate: null,
    monthlyPrice: 75000,
    billingCurrency: 'XOF',
    billingCycle: 'YEARLY',
    maxUsers: 50,
    maxProducts: 10000,
    maxStores: 5,
    maxOrdersPerMonth: 50000,
    storageQuotaGB: 50,
    featureInventory: true,
    featureOrders: true,
    featureDelivery: true,
    featureSuppliers: true,
    featureAdvancedReports: true,
    featurePromotions: true,
    featureMultiStore: true,
    featureApi: true,
    featureAccounting: true,
    defaultLanguage: 'fr',
    timezone: 'Africa/Abidjan',
    dateFormat: 'DD/MM/YYYY',
    primaryColor: '#1565C0',
    secondaryColor: '#E65100',
  },
  {
    tenantCode: 'PHSP-003',
    name: 'Pharmacie Santé Plus',
    legalName: 'SARL Pharmacie Santé Plus',
    registrationNumber: 'CI-YAM-2024-0789',
    taxId: 'CI0005551234',
    businessType: 'PHARMACY',
    status: 'ACTIVE',
    subscriptionPlan: 'STARTER',
    email: 'pharma@santeplus.ci',
    phone: '+225 27 30 64 55 77',
    website: 'https://santeplus.ci',
    address: 'Avenue Houphouët-Boigny',
    city: 'Yamoussoukro',
    state: 'Lacs',
    postalCode: '01 BP 999',
    country: 'CI',
    ownerName: 'Dr. Fatou Traoré',
    ownerEmail: 'fatou.traore@santeplus.ci',
    ownerPhone: '+225 07 55 66 77 88',
    subscriptionStartDate: new Date('2024-03-01'),
    subscriptionEndDate: new Date('2025-03-01'),
    trialEndDate: new Date('2024-04-01'),
    monthlyPrice: 15000,
    billingCurrency: 'XOF',
    billingCycle: 'MONTHLY',
    maxUsers: 5,
    maxProducts: 200,
    maxStores: 1,
    maxOrdersPerMonth: 2000,
    storageQuotaGB: 2,
    featureInventory: true,
    featureOrders: true,
    featureDelivery: false,
    featureSuppliers: true,
    featureAdvancedReports: false,
    featurePromotions: false,
    featureMultiStore: false,
    featureApi: false,
    featureAccounting: false,
    defaultLanguage: 'fr',
    timezone: 'Africa/Abidjan',
    dateFormat: 'DD/MM/YYYY',
    primaryColor: '#00897B',
    secondaryColor: '#FFFFFF',
  },
  {
    tenantCode: 'RAYA-CG-001',
    name: 'RAYA Distribution Congo',
    legalName: 'SARL RAYA Distribution',
    registrationNumber: 'CG-BZV-2025-0001',
    taxId: 'CG0001234567',
    businessType: 'BOUTIQUE',
    status: 'ACTIVE',
    subscriptionPlan: 'PROFESSIONAL',
    email: 'contact@raya.cg',
    phone: '+242 06 500 0001',
    website: 'https://rayamanager.online',
    address: 'Avenue de la Paix, Centre-Ville',
    city: 'Brazzaville',
    state: 'Brazzaville',
    postalCode: 'BP 1234',
    country: 'CG',
    ownerName: 'Jean-Pierre Mokonzi',
    ownerEmail: 'jpmokonzi@raya.cg',
    ownerPhone: '+242 06 500 0001',
    subscriptionStartDate: new Date('2025-01-01'),
    subscriptionEndDate: new Date('2026-12-31'),
    trialEndDate: null,
    monthlyPrice: 25000,
    billingCurrency: 'XAF',
    billingCycle: 'MONTHLY',
    maxUsers: 10,
    maxProducts: 500,
    maxStores: 3,
    maxOrdersPerMonth: 5000,
    storageQuotaGB: 5,
    featureInventory: true,
    featureOrders: true,
    featureDelivery: true,
    featureSuppliers: true,
    featureAdvancedReports: true,
    featurePromotions: true,
    featureMultiStore: true,
    featureApi: true,
    featureAccounting: false,
    defaultLanguage: 'fr',
    timezone: 'Africa/Brazzaville',
    dateFormat: 'DD/MM/YYYY',
    primaryColor: '#6366F1',
    secondaryColor: '#F59E0B',
  },
];

// ============================================================================
// USERS (per tenant) — Le mot de passe par défaut est "Password123!"
// ============================================================================
export const usersData = [
  // === Tenant 1: Boutique Chez Awa ===
  {
    tenantId: '1',
    email: 'awa.kone@chezawa.ci',
    username: 'awa.kone',
    role: 'PDG',
    firstName: 'Awa',
    lastName: 'Koné',
    phone: '+225 07 08 09 10 11',
    status: 'active',
  },
  {
    tenantId: '1',
    email: 'sekou.coulibaly@chezawa.ci',
    username: 'sekou.coulibaly',
    role: 'MANAGER',
    firstName: 'Sékou',
    lastName: 'Coulibaly',
    phone: '+225 05 11 22 33 44',
    status: 'active',
  },
  {
    tenantId: '1',
    email: 'aminata.bamba@chezawa.ci',
    username: 'aminata.bamba',
    role: 'VENDEUR',
    firstName: 'Aminata',
    lastName: 'Bamba',
    phone: '+225 07 22 33 44 55',
    status: 'active',
  },
  {
    tenantId: '1',
    email: 'ibrahim.toure@chezawa.ci',
    username: 'ibrahim.toure',
    role: 'VENDEUR',
    firstName: 'Ibrahim',
    lastName: 'Touré',
    phone: '+225 05 33 44 55 66',
    status: 'active',
  },
  {
    tenantId: '1',
    email: 'mariam.sylla@chezawa.ci',
    username: 'mariam.sylla',
    role: 'VENDEUR',
    firstName: 'Mariam',
    lastName: 'Sylla',
    phone: '+225 07 44 55 66 77',
    status: 'active',
  },

  // === Tenant 2: Super Marché Le Bon Prix ===
  {
    tenantId: '2',
    email: 'moussa.diallo@lebonprix.ci',
    username: 'moussa.diallo',
    role: 'PDG',
    firstName: 'Moussa',
    lastName: 'Diallo',
    phone: '+225 07 77 88 99 00',
    status: 'active',
  },
  {
    tenantId: '2',
    email: 'fatoumata.keita@lebonprix.ci',
    username: 'fatoumata.keita',
    role: 'MANAGER',
    firstName: 'Fatoumata',
    lastName: 'Keita',
    phone: '+225 05 88 99 00 11',
    status: 'active',
  },
  {
    tenantId: '2',
    email: 'oumar.sangare@lebonprix.ci',
    username: 'oumar.sangare',
    role: 'MANAGER',
    firstName: 'Oumar',
    lastName: 'Sangaré',
    phone: '+225 07 99 00 11 22',
    status: 'active',
  },
  {
    tenantId: '2',
    email: 'kadiatou.traore@lebonprix.ci',
    username: 'kadiatou.traore',
    role: 'VENDEUR',
    firstName: 'Kadiatou',
    lastName: 'Traoré',
    phone: '+225 05 00 11 22 33',
    status: 'active',
  },
  {
    tenantId: '2',
    email: 'adama.cisse@lebonprix.ci',
    username: 'adama.cisse',
    role: 'VENDEUR',
    firstName: 'Adama',
    lastName: 'Cissé',
    phone: '+225 07 11 22 33 44',
    status: 'active',
  },
  {
    tenantId: '2',
    email: 'salimatou.barry@lebonprix.ci',
    username: 'salimatou.barry',
    role: 'VENDEUR',
    firstName: 'Salimatou',
    lastName: 'Barry',
    phone: '+225 05 22 33 44 55',
    status: 'active',
  },
  {
    tenantId: '2',
    email: 'mamadou.camara@lebonprix.ci',
    username: 'mamadou.camara',
    role: 'VENDEUR',
    firstName: 'Mamadou',
    lastName: 'Camara',
    phone: '+225 07 33 44 55 66',
    status: 'active',
  },

  // === Tenant 3: Pharmacie Santé Plus ===
  {
    tenantId: '3',
    email: 'fatou.traore@santeplus.ci',
    username: 'fatou.traore',
    role: 'PDG',
    firstName: 'Fatou',
    lastName: 'Traoré',
    phone: '+225 07 55 66 77 88',
    status: 'active',
  },
  {
    tenantId: '3',
    email: 'aboubacar.diakite@santeplus.ci',
    username: 'aboubacar.diakite',
    role: 'MANAGER',
    firstName: 'Aboubacar',
    lastName: 'Diakité',
    phone: '+225 05 66 77 88 99',
    status: 'active',
  },
  {
    tenantId: '3',
    email: 'rokia.kone@santeplus.ci',
    username: 'rokia.kone',
    role: 'VENDEUR',
    firstName: 'Rokia',
    lastName: 'Koné',
    phone: '+225 07 77 88 99 00',
    status: 'active',
  },
  {
    tenantId: '3',
    email: 'drissa.ouattara@santeplus.ci',
    username: 'drissa.ouattara',
    role: 'VENDEUR',
    firstName: 'Drissa',
    lastName: 'Ouattara',
    phone: '+225 05 88 99 00 11',
    status: 'active',
  },

  // === Tenant 4: RAYA Distribution Congo (comptes démo — identiques au fichier HTML) ===
  {
    tenantId: '4',
    email: 'jpmokonzi@raya.cg',
    username: 'jpmokonzi',
    role: 'PDG',
    firstName: 'Jean-Pierre',
    lastName: 'Mokonzi',
    phone: '+242 06 500 0001',
    status: 'active',
  },
  {
    tenantId: '4',
    email: 'mloundou@raya.cg',
    username: 'mloundou',
    role: 'MANAGER',
    firstName: 'Marie',
    lastName: 'Loundou',
    phone: '+242 06 500 0002',
    status: 'active',
  },
  {
    tenantId: '4',
    email: 'pnzaba@raya.cg',
    username: 'pnzaba',
    role: 'GESTIONNAIRE',
    firstName: 'Patrick',
    lastName: 'Nzaba',
    phone: '+242 06 500 0003',
    status: 'active',
  },
  {
    tenantId: '4',
    email: 'ambongo@raya.cg',
    username: 'ambongo',
    role: 'VENDEUR',
    firstName: 'Amara',
    lastName: 'Mbongo',
    phone: '+242 06 500 0004',
    status: 'active',
  },
  {
    tenantId: '4',
    email: 'dkouma@raya.cg',
    username: 'dkouma',
    role: 'LIVREUR',
    firstName: 'David',
    lastName: 'Kouma',
    phone: '+242 06 500 0005',
    status: 'active',
  },
  {
    tenantId: '4',
    email: 'sokana@raya.cg',
    username: 'sokana',
    role: 'GESTIONNAIRE',
    firstName: 'Sophie',
    lastName: 'Okana',
    phone: '+242 06 500 0006',
    status: 'active',
  },
  {
    tenantId: '4',
    email: 'jsamba@raya.cg',
    username: 'jsamba',
    role: 'VENDEUR',
    firstName: 'Jérôme',
    lastName: 'Samba',
    phone: '+242 06 500 0007',
    status: 'active',
  },
  {
    tenantId: '4',
    email: 'emoussia@raya.cg',
    username: 'emoussia',
    role: 'LIVREUR',
    firstName: 'Émile',
    lastName: 'Moussia',
    phone: '+242 06 500 0008',
    status: 'active',
  },
];

// ============================================================================
// CATEGORIES (per tenant — slug unique globalement)
// ============================================================================
export const categoriesData = [
  // === Tenant 1: Boutique Chez Awa ===
  {
    tenantId: '1',
    name: 'Alimentation',
    slug: 'bawa-alimentation',
    description: 'Produits alimentaires de base',
    iconName: 'restaurant',
    colorCode: '#4CAF50',
    sortOrder: 1,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Boissons',
    slug: 'bawa-boissons',
    description: 'Boissons fraîches et chaudes',
    iconName: 'local_drink',
    colorCode: '#2196F3',
    sortOrder: 2,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Hygiène & Beauté',
    slug: 'bawa-hygiene-beaute',
    description: "Produits d'hygiène et soins corporels",
    iconName: 'spa',
    colorCode: '#E91E63',
    sortOrder: 3,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Nettoyage',
    slug: 'bawa-nettoyage',
    description: "Produits d'entretien ménager",
    iconName: 'cleaning_services',
    colorCode: '#00BCD4',
    sortOrder: 4,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Épicerie',
    slug: 'bawa-epicerie',
    description: 'Condiments, épices et assaisonnements',
    iconName: 'kitchen',
    colorCode: '#FF9800',
    sortOrder: 5,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Confiseries',
    slug: 'bawa-confiseries',
    description: 'Bonbons, chocolats et snacks',
    iconName: 'cake',
    colorCode: '#9C27B0',
    sortOrder: 6,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Bébé & Enfant',
    slug: 'bawa-bebe-enfant',
    description: 'Couches, lait bébé et accessoires',
    iconName: 'child_care',
    colorCode: '#FFEB3B',
    sortOrder: 7,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Divers',
    slug: 'bawa-divers',
    description: 'Articles divers et accessoires',
    iconName: 'category',
    colorCode: '#607D8B',
    sortOrder: 8,
    isActive: true,
  },

  // === Tenant 2: Super Marché Le Bon Prix ===
  {
    tenantId: '2',
    name: 'Fruits & Légumes',
    slug: 'smbp-fruits-legumes',
    description: 'Fruits et légumes frais locaux et importés',
    iconName: 'eco',
    colorCode: '#4CAF50',
    sortOrder: 1,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Boulangerie & Pâtisserie',
    slug: 'smbp-boulangerie',
    description: 'Pains, viennoiseries et gâteaux',
    iconName: 'bakery_dining',
    colorCode: '#8D6E63',
    sortOrder: 2,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Boucherie & Poissonnerie',
    slug: 'smbp-boucherie-poisson',
    description: 'Viandes fraîches et poissons',
    iconName: 'set_meal',
    colorCode: '#D32F2F',
    sortOrder: 3,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Produits Laitiers',
    slug: 'smbp-produits-laitiers',
    description: 'Lait, yaourts, fromages',
    iconName: 'egg',
    colorCode: '#FFF9C4',
    sortOrder: 4,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Épicerie Fine',
    slug: 'smbp-epicerie-fine',
    description: 'Conserves, huiles, sauces et condiments premium',
    iconName: 'kitchen',
    colorCode: '#FF9800',
    sortOrder: 5,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Boissons & Jus',
    slug: 'smbp-boissons-jus',
    description: 'Eaux, sodas, jus et boissons alcoolisées',
    iconName: 'local_bar',
    colorCode: '#2196F3',
    sortOrder: 6,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Surgelés',
    slug: 'smbp-surgeles',
    description: 'Produits surgelés et glaces',
    iconName: 'ac_unit',
    colorCode: '#B3E5FC',
    sortOrder: 7,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Hygiène & Entretien',
    slug: 'smbp-hygiene-entretien',
    description: "Produits d'hygiène et nettoyage",
    iconName: 'cleaning_services',
    colorCode: '#00BCD4',
    sortOrder: 8,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Électroménager',
    slug: 'smbp-electromenager',
    description: 'Petit et gros électroménager',
    iconName: 'kitchen',
    colorCode: '#78909C',
    sortOrder: 9,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Textile & Mode',
    slug: 'smbp-textile-mode',
    description: 'Vêtements et accessoires de mode',
    iconName: 'checkroom',
    colorCode: '#AB47BC',
    sortOrder: 10,
    isActive: true,
  },

  // === Tenant 3: Pharmacie Santé Plus ===
  {
    tenantId: '3',
    name: 'Médicaments',
    slug: 'phsp-medicaments',
    description: 'Médicaments sur ordonnance et en vente libre',
    iconName: 'medication',
    colorCode: '#F44336',
    sortOrder: 1,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Parapharmacie',
    slug: 'phsp-parapharmacie',
    description: 'Compléments alimentaires et soins',
    iconName: 'healing',
    colorCode: '#4CAF50',
    sortOrder: 2,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Hygiène Corporelle',
    slug: 'phsp-hygiene-corporelle',
    description: 'Savons, dentifrices, déodorants',
    iconName: 'spa',
    colorCode: '#00BCD4',
    sortOrder: 3,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Bébé & Maternité',
    slug: 'phsp-bebe-maternite',
    description: 'Soins bébé, lait, couches, grossesse',
    iconName: 'child_care',
    colorCode: '#FFEB3B',
    sortOrder: 4,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Cosmétique & Beauté',
    slug: 'phsp-cosmetique-beaute',
    description: 'Soins visage, corps et maquillage',
    iconName: 'face',
    colorCode: '#E91E63',
    sortOrder: 5,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Nutrition & Bien-être',
    slug: 'phsp-nutrition-bienetre',
    description: 'Vitamines, protéines, tisanes',
    iconName: 'fitness_center',
    colorCode: '#FF9800',
    sortOrder: 6,
    isActive: true,
  },
];

// ============================================================================
// PRODUCTS (per tenant — sku unique globalement)
// ============================================================================
export const productsData = [
  // === Tenant 1: Boutique Chez Awa (produits de boutique ivoirienne) ===
  {
    tenantId: '1',
    name: "Riz Brisé Uncle Ben's 5kg",
    sku: 'BAWA-RIZ-001',
    barcode: '3017760000017',
    categorySlug: 'bawa-alimentation',
    purchasePrice: 2800,
    sellingPrice: 3500,
    stockQuantity: 45,
    minStockLevel: 10,
    maxStockLevel: 100,
    unit: 'sac',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Huile de palme raffinée 1L',
    sku: 'BAWA-HUI-002',
    barcode: '6001234567890',
    categorySlug: 'bawa-alimentation',
    purchasePrice: 800,
    sellingPrice: 1000,
    stockQuantity: 60,
    minStockLevel: 15,
    maxStockLevel: 120,
    unit: 'bouteille',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Sucre en poudre 1kg',
    sku: 'BAWA-SUC-003',
    barcode: '6009876543210',
    categorySlug: 'bawa-alimentation',
    purchasePrice: 600,
    sellingPrice: 750,
    stockQuantity: 80,
    minStockLevel: 20,
    maxStockLevel: 150,
    unit: 'paquet',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Lait Nido 400g',
    sku: 'BAWA-LAI-004',
    barcode: '7613033812354',
    categorySlug: 'bawa-alimentation',
    purchasePrice: 2500,
    sellingPrice: 3200,
    stockQuantity: 30,
    minStockLevel: 8,
    maxStockLevel: 60,
    unit: 'boîte',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Coca-Cola 1.5L',
    sku: 'BAWA-COC-005',
    barcode: '5449000000996',
    categorySlug: 'bawa-boissons',
    purchasePrice: 400,
    sellingPrice: 600,
    stockQuantity: 100,
    minStockLevel: 20,
    maxStockLevel: 200,
    unit: 'bouteille',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Eau Awa 1.5L',
    sku: 'BAWA-EAU-006',
    barcode: '6001112223334',
    categorySlug: 'bawa-boissons',
    purchasePrice: 150,
    sellingPrice: 250,
    stockQuantity: 200,
    minStockLevel: 50,
    maxStockLevel: 500,
    unit: 'bouteille',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Savon Palmolive 100g',
    sku: 'BAWA-SAV-007',
    barcode: '8718951087897',
    categorySlug: 'bawa-hygiene-beaute',
    purchasePrice: 300,
    sellingPrice: 500,
    stockQuantity: 75,
    minStockLevel: 15,
    maxStockLevel: 150,
    unit: 'pièce',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Dentifrice Colgate 100ml',
    sku: 'BAWA-DEN-008',
    barcode: '8714789456123',
    categorySlug: 'bawa-hygiene-beaute',
    purchasePrice: 500,
    sellingPrice: 750,
    stockQuantity: 40,
    minStockLevel: 10,
    maxStockLevel: 80,
    unit: 'tube',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Javel Madar 1L',
    sku: 'BAWA-JAV-009',
    barcode: '6005551112223',
    categorySlug: 'bawa-nettoyage',
    purchasePrice: 350,
    sellingPrice: 500,
    stockQuantity: 50,
    minStockLevel: 10,
    maxStockLevel: 100,
    unit: 'bouteille',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Cube Maggi x100',
    sku: 'BAWA-MAG-010',
    barcode: '7613287261045',
    categorySlug: 'bawa-epicerie',
    purchasePrice: 1000,
    sellingPrice: 1500,
    stockQuantity: 35,
    minStockLevel: 8,
    maxStockLevel: 70,
    unit: 'boîte',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Bonbon Menthe Valda',
    sku: 'BAWA-BON-011',
    barcode: '3401096841245',
    categorySlug: 'bawa-confiseries',
    purchasePrice: 100,
    sellingPrice: 150,
    stockQuantity: 120,
    minStockLevel: 25,
    maxStockLevel: 250,
    unit: 'sachet',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Couches Pampers T3 x30',
    sku: 'BAWA-COU-012',
    barcode: '4015400838104',
    categorySlug: 'bawa-bebe-enfant',
    purchasePrice: 4000,
    sellingPrice: 5500,
    stockQuantity: 20,
    minStockLevel: 5,
    maxStockLevel: 40,
    unit: 'paquet',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Pile AA Energizer x4',
    sku: 'BAWA-PIL-013',
    barcode: '7638900247893',
    categorySlug: 'bawa-divers',
    purchasePrice: 800,
    sellingPrice: 1200,
    stockQuantity: 25,
    minStockLevel: 5,
    maxStockLevel: 50,
    unit: 'paquet',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '1',
    name: 'Tomate concentrée Gino 400g',
    sku: 'BAWA-TOM-014',
    barcode: '5011234100013',
    categorySlug: 'bawa-epicerie',
    purchasePrice: 450,
    sellingPrice: 650,
    stockQuantity: 55,
    minStockLevel: 12,
    maxStockLevel: 100,
    unit: 'boîte',
    taxRate: 0,
    isActive: true,
  },

  // === Tenant 2: Super Marché Le Bon Prix ===
  {
    tenantId: '2',
    name: 'Banane Plantain (kg)',
    sku: 'SMBP-BPL-001',
    barcode: '2001234567890',
    categorySlug: 'smbp-fruits-legumes',
    purchasePrice: 300,
    sellingPrice: 500,
    stockQuantity: 200,
    minStockLevel: 30,
    maxStockLevel: 400,
    unit: 'kg',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Tomate fraîche (kg)',
    sku: 'SMBP-TOM-002',
    barcode: '2001234567891',
    categorySlug: 'smbp-fruits-legumes',
    purchasePrice: 500,
    sellingPrice: 800,
    stockQuantity: 100,
    minStockLevel: 20,
    maxStockLevel: 200,
    unit: 'kg',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Avocat (pièce)',
    sku: 'SMBP-AVO-003',
    barcode: '2001234567892',
    categorySlug: 'smbp-fruits-legumes',
    purchasePrice: 200,
    sellingPrice: 350,
    stockQuantity: 80,
    minStockLevel: 15,
    maxStockLevel: 150,
    unit: 'pièce',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Pain baguette tradition',
    sku: 'SMBP-PAI-004',
    barcode: '2101234567890',
    categorySlug: 'smbp-boulangerie',
    purchasePrice: 100,
    sellingPrice: 150,
    stockQuantity: 300,
    minStockLevel: 50,
    maxStockLevel: 500,
    unit: 'pièce',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Poulet entier fermier (kg)',
    sku: 'SMBP-POU-005',
    barcode: '2201234567890',
    categorySlug: 'smbp-boucherie-poisson',
    purchasePrice: 2000,
    sellingPrice: 3000,
    stockQuantity: 40,
    minStockLevel: 10,
    maxStockLevel: 80,
    unit: 'kg',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Poisson Capitaine frais (kg)',
    sku: 'SMBP-CAP-006',
    barcode: '2201234567891',
    categorySlug: 'smbp-boucherie-poisson',
    purchasePrice: 3500,
    sellingPrice: 5000,
    stockQuantity: 25,
    minStockLevel: 5,
    maxStockLevel: 50,
    unit: 'kg',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Yaourt Yoplait Nature x4',
    sku: 'SMBP-YAO-007',
    barcode: '3329770044425',
    categorySlug: 'smbp-produits-laitiers',
    purchasePrice: 800,
    sellingPrice: 1200,
    stockQuantity: 60,
    minStockLevel: 15,
    maxStockLevel: 120,
    unit: 'pack',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '2',
    name: "Huile d'olive extra vierge 1L",
    sku: 'SMBP-HOL-008',
    barcode: '8001234567890',
    categorySlug: 'smbp-epicerie-fine',
    purchasePrice: 3000,
    sellingPrice: 4500,
    stockQuantity: 35,
    minStockLevel: 8,
    maxStockLevel: 70,
    unit: 'bouteille',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Jus de Bissap 1L',
    sku: 'SMBP-BIS-009',
    barcode: '6001234500001',
    categorySlug: 'smbp-boissons-jus',
    purchasePrice: 500,
    sellingPrice: 800,
    stockQuantity: 90,
    minStockLevel: 20,
    maxStockLevel: 180,
    unit: 'bouteille',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Bière Flag 65cl',
    sku: 'SMBP-FLG-010',
    barcode: '6001234500002',
    categorySlug: 'smbp-boissons-jus',
    purchasePrice: 400,
    sellingPrice: 700,
    stockQuantity: 150,
    minStockLevel: 30,
    maxStockLevel: 300,
    unit: 'bouteille',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Glace vanille Magnum 1L',
    sku: 'SMBP-GLA-011',
    barcode: '8722700188483',
    categorySlug: 'smbp-surgeles',
    purchasePrice: 2500,
    sellingPrice: 3800,
    stockQuantity: 20,
    minStockLevel: 5,
    maxStockLevel: 40,
    unit: 'bac',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Lessive Omo 5kg',
    sku: 'SMBP-LES-012',
    barcode: '6001087356572',
    categorySlug: 'smbp-hygiene-entretien',
    purchasePrice: 4500,
    sellingPrice: 6000,
    stockQuantity: 30,
    minStockLevel: 8,
    maxStockLevel: 60,
    unit: 'sac',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Ventilateur sur pied 16"',
    sku: 'SMBP-VEN-013',
    barcode: '8901234567890',
    categorySlug: 'smbp-electromenager',
    purchasePrice: 12000,
    sellingPrice: 18000,
    stockQuantity: 15,
    minStockLevel: 3,
    maxStockLevel: 30,
    unit: 'pièce',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Pagne Wax 6 yards',
    sku: 'SMBP-PAG-014',
    barcode: '8901234567891',
    categorySlug: 'smbp-textile-mode',
    purchasePrice: 5000,
    sellingPrice: 8500,
    stockQuantity: 25,
    minStockLevel: 5,
    maxStockLevel: 50,
    unit: 'pièce',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '2',
    name: 'Attiéké précuit 500g',
    sku: 'SMBP-ATT-015',
    barcode: '6001234500003',
    categorySlug: 'smbp-fruits-legumes',
    purchasePrice: 300,
    sellingPrice: 500,
    stockQuantity: 70,
    minStockLevel: 15,
    maxStockLevel: 140,
    unit: 'sachet',
    taxRate: 0,
    isActive: true,
  },

  // === Tenant 3: Pharmacie Santé Plus ===
  {
    tenantId: '3',
    name: 'Paracétamol 500mg x16',
    sku: 'PHSP-PAR-001',
    barcode: '3400930000014',
    categorySlug: 'phsp-medicaments',
    purchasePrice: 500,
    sellingPrice: 1000,
    stockQuantity: 200,
    minStockLevel: 30,
    maxStockLevel: 400,
    unit: 'boîte',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Amoxicilline 500mg x12',
    sku: 'PHSP-AMO-002',
    barcode: '3400930000021',
    categorySlug: 'phsp-medicaments',
    purchasePrice: 1500,
    sellingPrice: 2500,
    stockQuantity: 80,
    minStockLevel: 15,
    maxStockLevel: 150,
    unit: 'boîte',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Ibuprofène 400mg x20',
    sku: 'PHSP-IBU-003',
    barcode: '3400930000038',
    categorySlug: 'phsp-medicaments',
    purchasePrice: 800,
    sellingPrice: 1500,
    stockQuantity: 120,
    minStockLevel: 20,
    maxStockLevel: 250,
    unit: 'boîte',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Vitamine C 1000mg effervescent x20',
    sku: 'PHSP-VIC-004',
    barcode: '3400930000045',
    categorySlug: 'phsp-parapharmacie',
    purchasePrice: 2000,
    sellingPrice: 3500,
    stockQuantity: 50,
    minStockLevel: 10,
    maxStockLevel: 100,
    unit: 'tube',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Gel hydroalcoolique 500ml',
    sku: 'PHSP-GEL-005',
    barcode: '3400930000052',
    categorySlug: 'phsp-hygiene-corporelle',
    purchasePrice: 1200,
    sellingPrice: 2000,
    stockQuantity: 60,
    minStockLevel: 12,
    maxStockLevel: 120,
    unit: 'flacon',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Couches Huggies T2 x40',
    sku: 'PHSP-COU-006',
    barcode: '5029053562896',
    categorySlug: 'phsp-bebe-maternite',
    purchasePrice: 3500,
    sellingPrice: 5000,
    stockQuantity: 25,
    minStockLevel: 5,
    maxStockLevel: 50,
    unit: 'paquet',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Lait bébé Gallia 1er âge 800g',
    sku: 'PHSP-LAI-007',
    barcode: '3041091428097',
    categorySlug: 'phsp-bebe-maternite',
    purchasePrice: 5000,
    sellingPrice: 7500,
    stockQuantity: 20,
    minStockLevel: 5,
    maxStockLevel: 40,
    unit: 'boîte',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Crème solaire SPF50 200ml',
    sku: 'PHSP-SOL-008',
    barcode: '3600523959563',
    categorySlug: 'phsp-cosmetique-beaute',
    purchasePrice: 4000,
    sellingPrice: 6500,
    stockQuantity: 15,
    minStockLevel: 3,
    maxStockLevel: 30,
    unit: 'tube',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Crème éclaircissante Caro Light',
    sku: 'PHSP-CAR-009',
    barcode: '6001234500010',
    categorySlug: 'phsp-cosmetique-beaute',
    purchasePrice: 2500,
    sellingPrice: 4000,
    stockQuantity: 30,
    minStockLevel: 5,
    maxStockLevel: 60,
    unit: 'pot',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Protéines Whey 1kg',
    sku: 'PHSP-PRO-010',
    barcode: '5060245609876',
    categorySlug: 'phsp-nutrition-bienetre',
    purchasePrice: 15000,
    sellingPrice: 22000,
    stockQuantity: 10,
    minStockLevel: 2,
    maxStockLevel: 20,
    unit: 'pot',
    taxRate: 18,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Tisane Nuit Calme x20',
    sku: 'PHSP-TIS-011',
    barcode: '3284390000011',
    categorySlug: 'phsp-nutrition-bienetre',
    purchasePrice: 1500,
    sellingPrice: 2500,
    stockQuantity: 35,
    minStockLevel: 8,
    maxStockLevel: 70,
    unit: 'boîte',
    taxRate: 0,
    isActive: true,
  },
  {
    tenantId: '3',
    name: 'Thermomètre digital',
    sku: 'PHSP-THE-012',
    barcode: '4015672104563',
    categorySlug: 'phsp-parapharmacie',
    purchasePrice: 3000,
    sellingPrice: 5000,
    stockQuantity: 18,
    minStockLevel: 3,
    maxStockLevel: 35,
    unit: 'pièce',
    taxRate: 18,
    isActive: true,
  },
];

// ============================================================================
// CUSTOMERS (per tenant)
// ============================================================================
export const customersData = [
  // === Tenant 1: Boutique Chez Awa ===
  {
    tenantId: '1',
    customerCode: 'BAWA-CLI-001',
    firstName: 'Adjoua',
    lastName: 'Konan',
    email: 'adjoua.konan@email.ci',
    phone: '+225 07 10 20 30 40',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'SILVER',
    loyaltyPoints: 250,
    totalOrders: 15,
    totalSpent: 45000,
  },
  {
    tenantId: '1',
    customerCode: 'BAWA-CLI-002',
    firstName: 'Yao',
    lastName: 'Koffi',
    email: 'yao.koffi@email.ci',
    phone: '+225 05 20 30 40 50',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'BRONZE',
    loyaltyPoints: 80,
    totalOrders: 5,
    totalSpent: 15000,
  },
  {
    tenantId: '1',
    customerCode: 'BAWA-CLI-003',
    firstName: 'Aïcha',
    lastName: 'Ouédraogo',
    email: null,
    phone: '+225 07 30 40 50 60',
    city: 'Abidjan',
    country: 'CI',
    status: 'VIP',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'GOLD',
    loyaltyPoints: 1200,
    totalOrders: 50,
    totalSpent: 250000,
  },
  {
    tenantId: '1',
    customerCode: 'BAWA-CLI-004',
    firstName: 'Restaurant',
    lastName: 'Le Maquis Central',
    email: 'maquis.central@email.ci',
    phone: '+225 27 22 10 20 30',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'BUSINESS',
    loyaltyTier: 'GOLD',
    loyaltyPoints: 800,
    totalOrders: 30,
    totalSpent: 180000,
    companyName: 'Le Maquis Central SARL',
  },
  {
    tenantId: '1',
    customerCode: 'BAWA-CLI-005',
    firstName: 'Lacina',
    lastName: 'Doumbia',
    email: null,
    phone: '+225 05 40 50 60 70',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'BRONZE',
    loyaltyPoints: 30,
    totalOrders: 3,
    totalSpent: 8000,
  },
  {
    tenantId: '1',
    customerCode: 'BAWA-CLI-006',
    firstName: 'Bintou',
    lastName: 'Sanogo',
    email: 'bintou.s@email.ci',
    phone: '+225 07 50 60 70 80',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'WHOLESALE',
    loyaltyTier: 'PLATINUM',
    loyaltyPoints: 3000,
    totalOrders: 100,
    totalSpent: 750000,
    companyName: 'Grossiste Sanogo',
  },

  // === Tenant 2: Super Marché Le Bon Prix ===
  {
    tenantId: '2',
    customerCode: 'SMBP-CLI-001',
    firstName: 'Eugène',
    lastName: 'Aka',
    email: 'eugene.aka@email.ci',
    phone: '+225 07 60 70 80 90',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'SILVER',
    loyaltyPoints: 500,
    totalOrders: 25,
    totalSpent: 120000,
  },
  {
    tenantId: '2',
    customerCode: 'SMBP-CLI-002',
    firstName: 'Marie-Claire',
    lastName: 'Ahou',
    email: 'mc.ahou@email.ci',
    phone: '+225 05 70 80 90 00',
    city: 'Abidjan',
    country: 'CI',
    status: 'VIP',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'PLATINUM',
    loyaltyPoints: 5000,
    totalOrders: 80,
    totalSpent: 500000,
  },
  {
    tenantId: '2',
    customerCode: 'SMBP-CLI-003',
    firstName: 'Hôtel',
    lastName: 'Ivoire Palace',
    email: 'achat@ivoirepalace.ci',
    phone: '+225 27 22 30 40 50',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'BUSINESS',
    loyaltyTier: 'PLATINUM',
    loyaltyPoints: 8000,
    totalOrders: 120,
    totalSpent: 2500000,
    companyName: 'Hôtel Ivoire Palace SA',
  },
  {
    tenantId: '2',
    customerCode: 'SMBP-CLI-004',
    firstName: 'Koné',
    lastName: 'Massa',
    email: null,
    phone: '+225 07 80 90 00 11',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'BRONZE',
    loyaltyPoints: 100,
    totalOrders: 8,
    totalSpent: 35000,
  },
  {
    tenantId: '2',
    customerCode: 'SMBP-CLI-005',
    firstName: 'Traiteur',
    lastName: "Délice d'Afrique",
    email: 'delice.afrique@email.ci',
    phone: '+225 05 90 00 11 22',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'BUSINESS',
    loyaltyTier: 'GOLD',
    loyaltyPoints: 2000,
    totalOrders: 45,
    totalSpent: 450000,
    companyName: "Délice d'Afrique SARL",
  },
  {
    tenantId: '2',
    customerCode: 'SMBP-CLI-006',
    firstName: 'Djeneba',
    lastName: 'Fofana',
    email: 'djeneba.f@email.ci',
    phone: '+225 07 00 11 22 33',
    city: 'Bouaké',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'SILVER',
    loyaltyPoints: 400,
    totalOrders: 18,
    totalSpent: 85000,
  },
  {
    tenantId: '2',
    customerCode: 'SMBP-CLI-007',
    firstName: 'Grossiste',
    lastName: 'Diaby Import-Export',
    email: 'diaby.import@email.ci',
    phone: '+225 27 22 40 50 60',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'WHOLESALE',
    loyaltyTier: 'PLATINUM',
    loyaltyPoints: 10000,
    totalOrders: 200,
    totalSpent: 5000000,
    companyName: 'Diaby Import-Export SA',
  },

  // === Tenant 3: Pharmacie Santé Plus ===
  {
    tenantId: '3',
    customerCode: 'PHSP-CLI-001',
    firstName: 'Yvonne',
    lastName: "N'Guessan",
    email: 'yvonne.ng@email.ci',
    phone: '+225 07 11 22 33 44',
    city: 'Yamoussoukro',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'SILVER',
    loyaltyPoints: 300,
    totalOrders: 20,
    totalSpent: 65000,
  },
  {
    tenantId: '3',
    customerCode: 'PHSP-CLI-002',
    firstName: 'Moustapha',
    lastName: 'Konaté',
    email: null,
    phone: '+225 05 12 23 34 45',
    city: 'Yamoussoukro',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'BRONZE',
    loyaltyPoints: 50,
    totalOrders: 4,
    totalSpent: 12000,
  },
  {
    tenantId: '3',
    customerCode: 'PHSP-CLI-003',
    firstName: 'Clinique',
    lastName: 'Les Palmiers',
    email: 'achats@cliniquepalmiers.ci',
    phone: '+225 27 30 50 60 70',
    city: 'Yamoussoukro',
    country: 'CI',
    status: 'VIP',
    customerType: 'BUSINESS',
    loyaltyTier: 'GOLD',
    loyaltyPoints: 2500,
    totalOrders: 60,
    totalSpent: 850000,
    companyName: 'Clinique Les Palmiers SARL',
  },
  {
    tenantId: '3',
    customerCode: 'PHSP-CLI-004',
    firstName: 'Salimata',
    lastName: 'Diabaté',
    email: 'salimata.d@email.ci',
    phone: '+225 07 23 34 45 56',
    city: 'Yamoussoukro',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'BRONZE',
    loyaltyPoints: 120,
    totalOrders: 10,
    totalSpent: 30000,
  },
  {
    tenantId: '3',
    customerCode: 'PHSP-CLI-005',
    firstName: 'Issouf',
    lastName: 'Bamba',
    email: null,
    phone: '+225 05 34 45 56 67',
    city: 'Bouaké',
    country: 'CI',
    status: 'ACTIVE',
    customerType: 'INDIVIDUAL',
    loyaltyTier: 'SILVER',
    loyaltyPoints: 450,
    totalOrders: 22,
    totalSpent: 75000,
  },
];

// ============================================================================
// SUPPLIERS (per tenant)
// ============================================================================
export const suppliersData = [
  // === Tenant 1: Boutique Chez Awa ===
  {
    tenantId: '1',
    supplierCode: 'BAWA-FRN-001',
    name: 'Prosuma Distribution',
    contactName: 'Jean-Marc Brou',
    email: 'commandes@prosuma.ci',
    phone: '+225 27 21 75 00 00',
    address: 'Zone Industrielle, Yopougon',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_30',
    currency: 'XOF',
    rating: 4.5,
    averageDeliveryDays: 3,
  },
  {
    tenantId: '1',
    supplierCode: 'BAWA-FRN-002',
    name: 'CDCI (Compagnie de Distribution)',
    contactName: 'Alassane Konaté',
    email: 'ventes@cdci.ci',
    phone: '+225 27 21 35 00 00',
    address: 'Rue des Entrepôts, Treichville',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_15',
    currency: 'XOF',
    rating: 4.2,
    averageDeliveryDays: 2,
  },
  {
    tenantId: '1',
    supplierCode: 'BAWA-FRN-003',
    name: "Nestlé Côte d'Ivoire",
    contactName: 'Cécile Yao',
    email: 'b2b@nestle.ci',
    phone: '+225 27 21 25 00 00',
    address: 'Boulevard de Vridi',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_30',
    currency: 'XOF',
    rating: 4.8,
    averageDeliveryDays: 5,
  },
  {
    tenantId: '1',
    supplierCode: 'BAWA-FRN-004',
    name: 'Unilever CI',
    contactName: 'Kader Diomandé',
    email: 'distribution@unilever.ci',
    phone: '+225 27 21 25 50 00',
    address: 'Zone Industrielle, Vridi',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_45',
    currency: 'XOF',
    rating: 4.0,
    averageDeliveryDays: 4,
  },

  // === Tenant 2: Super Marché Le Bon Prix ===
  {
    tenantId: '2',
    supplierCode: 'SMBP-FRN-001',
    name: 'COQIVOIRE',
    contactName: 'Paul Ehui',
    email: 'commandes@coqivoire.ci',
    phone: '+225 27 21 26 00 00',
    address: 'Zone Industrielle, Yopougon',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_30',
    currency: 'XOF',
    rating: 4.3,
    averageDeliveryDays: 2,
  },
  {
    tenantId: '2',
    supplierCode: 'SMBP-FRN-002',
    name: 'SIPRA (Aviculture)',
    contactName: 'Mariam Diabaté',
    email: 'ventes@sipra.ci',
    phone: '+225 27 21 24 00 00',
    address: "Route d'Anyama",
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_15',
    currency: 'XOF',
    rating: 4.6,
    averageDeliveryDays: 1,
  },
  {
    tenantId: '2',
    supplierCode: 'SMBP-FRN-003',
    name: 'SOLIBRA (Brasserie)',
    contactName: 'Koffi Assi',
    email: 'distribution@solibra.ci',
    phone: '+225 27 21 23 00 00',
    address: 'Boulevard de Marseille',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_30',
    currency: 'XOF',
    rating: 4.7,
    averageDeliveryDays: 2,
  },
  {
    tenantId: '2',
    supplierCode: 'SMBP-FRN-004',
    name: 'Société Ivoirienne de Cacao',
    contactName: 'Ousmane Sidibé',
    email: 'export@sic-cacao.ci',
    phone: '+225 27 21 22 00 00',
    address: 'San Pedro Port',
    city: 'San Pedro',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_60',
    currency: 'XOF',
    rating: 4.1,
    averageDeliveryDays: 7,
  },
  {
    tenantId: '2',
    supplierCode: 'SMBP-FRN-005',
    name: 'Manutention Africaine',
    contactName: 'Bakary Camara',
    email: 'logistique@manuaf.ci',
    phone: '+225 27 21 21 00 00',
    address: 'Port Autonome',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_45',
    currency: 'XOF',
    rating: 3.8,
    averageDeliveryDays: 10,
  },

  // === Tenant 3: Pharmacie Santé Plus ===
  {
    tenantId: '3',
    supplierCode: 'PHSP-FRN-001',
    name: 'COPHARMED',
    contactName: 'Dr. Amadou Bah',
    email: 'commandes@copharmed.ci',
    phone: '+225 27 22 44 00 00',
    address: 'Plateau Médical, Zone 3',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_30',
    currency: 'XOF',
    rating: 4.9,
    averageDeliveryDays: 3,
  },
  {
    tenantId: '3',
    supplierCode: 'PHSP-FRN-002',
    name: "Laborex Côte d'Ivoire",
    contactName: 'Brigitte Koua',
    email: 'distribution@laborex.ci',
    phone: '+225 27 22 45 00 00',
    address: 'Zone Franche, Vridi',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_45',
    currency: 'XOF',
    rating: 4.7,
    averageDeliveryDays: 4,
  },
  {
    tenantId: '3',
    supplierCode: 'PHSP-FRN-003',
    name: 'DPCI (Distribution Pharma)',
    contactName: 'Seydou Kouyaté',
    email: 'ventes@dpci.ci',
    phone: '+225 27 22 46 00 00',
    address: 'Zone Industrielle Yopougon',
    city: 'Abidjan',
    country: 'CI',
    status: 'ACTIVE',
    paymentTerms: 'NET_15',
    currency: 'XOF',
    rating: 4.4,
    averageDeliveryDays: 2,
  },
];

// ============================================================================
// ORDERS (per tenant — avec items dénormalisés)
// ============================================================================
export interface SeedOrderItem {
  productSku: string;
  quantity: number;
  discountPercent?: number;
}

export interface SeedOrder {
  tenantId: string;
  orderNumber: string;
  customerCode: string | null;
  customerName: string;
  customerPhone: string;
  status: string;
  paymentStatus: string;
  paymentMethod: string;
  notes: string | null;
  createdByEmail: string;
  items: SeedOrderItem[];
}

export const ordersData: SeedOrder[] = [
  // === Tenant 1: Boutique Chez Awa ===
  {
    tenantId: '1',
    orderNumber: 'BAWA-ORD-2024-0001',
    customerCode: 'BAWA-CLI-001',
    customerName: 'Adjoua Konan',
    customerPhone: '+225 07 10 20 30 40',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    notes: null,
    createdByEmail: 'aminata.bamba@chezawa.ci',
    items: [
      { productSku: 'BAWA-RIZ-001', quantity: 2 },
      { productSku: 'BAWA-HUI-002', quantity: 3 },
      { productSku: 'BAWA-MAG-010', quantity: 1 },
    ],
  },
  {
    tenantId: '1',
    orderNumber: 'BAWA-ORD-2024-0002',
    customerCode: 'BAWA-CLI-003',
    customerName: 'Aïcha Ouédraogo',
    customerPhone: '+225 07 30 40 50 60',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'MOBILE',
    notes: 'Livraison dans la cour',
    createdByEmail: 'ibrahim.toure@chezawa.ci',
    items: [
      { productSku: 'BAWA-COC-005', quantity: 6 },
      { productSku: 'BAWA-EAU-006', quantity: 12 },
      { productSku: 'BAWA-SUC-003', quantity: 2 },
      { productSku: 'BAWA-LAI-004', quantity: 1 },
    ],
  },
  {
    tenantId: '1',
    orderNumber: 'BAWA-ORD-2024-0003',
    customerCode: 'BAWA-CLI-004',
    customerName: 'Le Maquis Central',
    customerPhone: '+225 27 22 10 20 30',
    status: 'CONFIRMED',
    paymentStatus: 'PARTIAL',
    paymentMethod: 'TRANSFER',
    notes: 'Commande hebdomadaire',
    createdByEmail: 'sekou.coulibaly@chezawa.ci',
    items: [
      { productSku: 'BAWA-RIZ-001', quantity: 10 },
      { productSku: 'BAWA-HUI-002', quantity: 20 },
      { productSku: 'BAWA-TOM-014', quantity: 15 },
      { productSku: 'BAWA-MAG-010', quantity: 5 },
    ],
  },
  {
    tenantId: '1',
    orderNumber: 'BAWA-ORD-2024-0004',
    customerCode: 'BAWA-CLI-006',
    customerName: 'Bintou Sanogo (Grossiste)',
    customerPhone: '+225 07 50 60 70 80',
    status: 'PROCESSING',
    paymentStatus: 'PENDING',
    paymentMethod: 'CREDIT',
    notes: 'Commande en gros mensuelle',
    createdByEmail: 'awa.kone@chezawa.ci',
    items: [
      { productSku: 'BAWA-SAV-007', quantity: 50 },
      { productSku: 'BAWA-DEN-008', quantity: 30 },
      { productSku: 'BAWA-JAV-009', quantity: 40 },
      { productSku: 'BAWA-COU-012', quantity: 20, discountPercent: 5 },
    ],
  },
  {
    tenantId: '1',
    orderNumber: 'BAWA-ORD-2024-0005',
    customerCode: null,
    customerName: 'Client Passage',
    customerPhone: '',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    notes: null,
    createdByEmail: 'mariam.sylla@chezawa.ci',
    items: [
      { productSku: 'BAWA-BON-011', quantity: 3 },
      { productSku: 'BAWA-PIL-013', quantity: 1 },
    ],
  },

  // === Tenant 2: Super Marché Le Bon Prix ===
  {
    tenantId: '2',
    orderNumber: 'SMBP-ORD-2024-0001',
    customerCode: 'SMBP-CLI-002',
    customerName: 'Marie-Claire Ahou',
    customerPhone: '+225 05 70 80 90 00',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    notes: null,
    createdByEmail: 'kadiatou.traore@lebonprix.ci',
    items: [
      { productSku: 'SMBP-BPL-001', quantity: 3 },
      { productSku: 'SMBP-POU-005', quantity: 2 },
      { productSku: 'SMBP-YAO-007', quantity: 4 },
      { productSku: 'SMBP-PAI-004', quantity: 6 },
    ],
  },
  {
    tenantId: '2',
    orderNumber: 'SMBP-ORD-2024-0002',
    customerCode: 'SMBP-CLI-003',
    customerName: 'Hôtel Ivoire Palace',
    customerPhone: '+225 27 22 30 40 50',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'TRANSFER',
    notes: 'Livraison cuisine hôtel',
    createdByEmail: 'oumar.sangare@lebonprix.ci',
    items: [
      { productSku: 'SMBP-POU-005', quantity: 20 },
      { productSku: 'SMBP-CAP-006', quantity: 15 },
      { productSku: 'SMBP-TOM-002', quantity: 10 },
      { productSku: 'SMBP-HOL-008', quantity: 5 },
      { productSku: 'SMBP-BIS-009', quantity: 24 },
    ],
  },
  {
    tenantId: '2',
    orderNumber: 'SMBP-ORD-2024-0003',
    customerCode: 'SMBP-CLI-005',
    customerName: "Délice d'Afrique",
    customerPhone: '+225 05 90 00 11 22',
    status: 'CONFIRMED',
    paymentStatus: 'PARTIAL',
    paymentMethod: 'TRANSFER',
    notes: 'Commander pour événement samedi',
    createdByEmail: 'fatoumata.keita@lebonprix.ci',
    items: [
      { productSku: 'SMBP-ATT-015', quantity: 50 },
      { productSku: 'SMBP-BPL-001', quantity: 30 },
      { productSku: 'SMBP-TOM-002', quantity: 15 },
      { productSku: 'SMBP-AVO-003', quantity: 20 },
    ],
  },
  {
    tenantId: '2',
    orderNumber: 'SMBP-ORD-2024-0004',
    customerCode: 'SMBP-CLI-007',
    customerName: 'Diaby Import-Export',
    customerPhone: '+225 27 22 40 50 60',
    status: 'PENDING',
    paymentStatus: 'PENDING',
    paymentMethod: 'CREDIT',
    notes: 'Grosse commande mensuelle',
    createdByEmail: 'moussa.diallo@lebonprix.ci',
    items: [
      { productSku: 'SMBP-FLG-010', quantity: 100 },
      { productSku: 'SMBP-BIS-009', quantity: 100 },
      { productSku: 'SMBP-LES-012', quantity: 30, discountPercent: 10 },
      { productSku: 'SMBP-PAG-014', quantity: 50, discountPercent: 5 },
    ],
  },
  {
    tenantId: '2',
    orderNumber: 'SMBP-ORD-2024-0005',
    customerCode: 'SMBP-CLI-001',
    customerName: 'Eugène Aka',
    customerPhone: '+225 07 60 70 80 90',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'MOBILE',
    notes: null,
    createdByEmail: 'adama.cisse@lebonprix.ci',
    items: [
      { productSku: 'SMBP-VEN-013', quantity: 1 },
      { productSku: 'SMBP-GLA-011', quantity: 2 },
    ],
  },
  {
    tenantId: '2',
    orderNumber: 'SMBP-ORD-2024-0006',
    customerCode: null,
    customerName: 'Client de passage',
    customerPhone: '',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    notes: null,
    createdByEmail: 'salimatou.barry@lebonprix.ci',
    items: [
      { productSku: 'SMBP-PAI-004', quantity: 2 },
      { productSku: 'SMBP-YAO-007', quantity: 1 },
    ],
  },

  // === Tenant 3: Pharmacie Santé Plus ===
  {
    tenantId: '3',
    orderNumber: 'PHSP-ORD-2024-0001',
    customerCode: 'PHSP-CLI-001',
    customerName: "Yvonne N'Guessan",
    customerPhone: '+225 07 11 22 33 44',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    notes: 'Ordonnance Dr. Koné',
    createdByEmail: 'rokia.kone@santeplus.ci',
    items: [
      { productSku: 'PHSP-PAR-001', quantity: 2 },
      { productSku: 'PHSP-AMO-002', quantity: 1 },
      { productSku: 'PHSP-VIC-004', quantity: 1 },
    ],
  },
  {
    tenantId: '3',
    orderNumber: 'PHSP-ORD-2024-0002',
    customerCode: 'PHSP-CLI-003',
    customerName: 'Clinique Les Palmiers',
    customerPhone: '+225 27 30 50 60 70',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'TRANSFER',
    notes: 'Commande mensuelle clinique',
    createdByEmail: 'aboubacar.diakite@santeplus.ci',
    items: [
      { productSku: 'PHSP-PAR-001', quantity: 50 },
      { productSku: 'PHSP-AMO-002', quantity: 30 },
      { productSku: 'PHSP-IBU-003', quantity: 40 },
      { productSku: 'PHSP-GEL-005', quantity: 20 },
      { productSku: 'PHSP-THE-012', quantity: 5 },
    ],
  },
  {
    tenantId: '3',
    orderNumber: 'PHSP-ORD-2024-0003',
    customerCode: 'PHSP-CLI-004',
    customerName: 'Salimata Diabaté',
    customerPhone: '+225 07 23 34 45 56',
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    paymentMethod: 'MOBILE',
    notes: null,
    createdByEmail: 'drissa.ouattara@santeplus.ci',
    items: [
      { productSku: 'PHSP-COU-006', quantity: 2 },
      { productSku: 'PHSP-LAI-007', quantity: 1 },
    ],
  },
  {
    tenantId: '3',
    orderNumber: 'PHSP-ORD-2024-0004',
    customerCode: null,
    customerName: 'Client de passage',
    customerPhone: '',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    notes: null,
    createdByEmail: 'rokia.kone@santeplus.ci',
    items: [
      { productSku: 'PHSP-SOL-008', quantity: 1 },
      { productSku: 'PHSP-CAR-009', quantity: 2 },
      { productSku: 'PHSP-TIS-011', quantity: 1 },
    ],
  },
  {
    tenantId: '3',
    orderNumber: 'PHSP-ORD-2024-0005',
    customerCode: 'PHSP-CLI-005',
    customerName: 'Issouf Bamba',
    customerPhone: '+225 05 34 45 56 67',
    status: 'PENDING',
    paymentStatus: 'PENDING',
    paymentMethod: 'CASH',
    notes: 'En attente retour labo',
    createdByEmail: 'fatou.traore@santeplus.ci',
    items: [
      { productSku: 'PHSP-PRO-010', quantity: 1 },
      { productSku: 'PHSP-VIC-004', quantity: 2 },
    ],
  },
];
